version: '3.1'

services:

  db:
    image: mariadb:10.5.13
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: challengerDbAdmin
      MARIADB_DATABASE: challengerDB
    ports:
      - 3306:3306  

    